name: Daily NFT Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'  # runs daily at 18:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      RPC_URL: ${{ secrets.RPC_URL }}
      CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
      PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
      PINATA_SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install system dependencies for canvas
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential librsvg2-dev

      - name: Install Node.js dependencies
        run: npm install

      - name: Run generate script
        run: node generate_gif.js

      - name: Upload to Pinata
        run: node upload_to_pinata.js

      - name: Mint NFT on chain
        run: node scripts/mint_and_list.js

      - name: Debug Secret Length
        run: |
          echo "PRIVATE_KEY length: ${#PRIVATE_KEY}"
          echo "RPC_URL length: ${#RPC_URL}"
          echo "CONTRACT_ADDRESS length: ${#CONTRACT_ADDRESS}"
          echo "PINATA_API_KEY length: ${#PINATA_API_KEY}"
          echo "PINATA_SECRET_API_KEY length: ${#PINATA_SECRET_API_KEY}"
