name: Daily NFT Bot

on:
  schedule:
    - cron: '0 10 * * *'   # every day at 10:00 UTC
  workflow_dispatch:      # allow manual trigger too

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate today's GIF
        run: node generate_gif.js

      - name: Upload to Pinata
        run: node upload_to_pinata.js

      - name: Mint NFT on chain
        run: node mint_and_list.js
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          RPC_URL: ${{ secrets.RPC_URL }}
          CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}

